# Problem 12
# Answer: 76576500

'''
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
'''

import math

def numberOfFactors(x):
	sqrt = int(math.ceil(math.sqrt(x))) + 1
	prime_factors = {}

	done = False
	while not done:
		done = True
		for i in xrange(2,sqrt):
			if (x % i == 0):
				if i in prime_factors:
					prime_factors[i] += 1
				else:
					prime_factors[i] = 1
				x = x/i
				done = False
				break
	
	if (x != 1):
		prime_factors[x] = 1

	count = 1
	for x in prime_factors:
		count *= (prime_factors[x]+1)
	return count

triangle = 0
num = 1
while numberOfFactors(triangle) <= 500:
	triangle += num
	num += 1

print triangle