# Problem 45
# Answer: 1533776805

'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

def isPentagonal(x):
	n1 = float(1)/6 + (float(1)/4 - 4 * float(3)/2 * -x)**0.5/3
	if int(n1) == n1:
		return True
	else:
		return False

def isTriangle(x):
	n1 = -float(1)/2 + (float(1)/4 - 4 * float(1/2) * -x)**0.5
	if int(n1) == n1:
		return True
	else:
		return False

def isHexagonal(x):
	n1 = float(1)/4 + (1 - 4 * 2 * -x)**0.5/4
	if int(n1) == n1:
		return True
	else:
		return False

triangle = []
pentagon = []
hexagon = []

for i in xrange(1,100000):
	triangle.append(float(i)*(i+1)/2)
	pentagon.append(float(i)*(3*i-1)/2)
	hexagon.append(float(i)*(2*i-1))

x = set(set(triangle).intersection(pentagon)).intersection(hexagon)
print int(list(x)[2])