# Problem 44
# Answer: 5482660

'''
Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk - Pj| is minimised; what is the value of D?
'''

def isPentagonal(x):
	n = float(1)/6 + (float(1)/4 - 4 * float(3)/2 * -x)**0.5/3
	if int(n) == n:
		return True
	else:
		return False

i = 0
found = False
while not found:
	i += 1
	x = float(i) * (3*i-1)/2
	z = i
	while z > 0:
		r = float(z) * (3*z-1)/2
		if isPentagonal(x-r) and isPentagonal(x+r):
			print int(x-r)
			found = True
			break
		z -= 1

